class Error:
    TOO_LARGE_RESPONSE = 'Response is too large. Be more specific in your request'
    NO_RESPONSE = 'Nothing found. Try another query'


class Translation:
    BIBLE = {
        'Amuzgo de Guerrero (AMU)': 'AMU',
        'Arabic Bible: Easy-to-Read Version (ERV-AR)': 'ERV-AR',
        'Ketab El Hayat (NAV)': 'NAV',
        'Awadhi Bible: Easy-to-Read Version (ERV-AWA)': 'ERV-AWA',
        '1940 Bulgarian Bible (BG1940)': 'BG1940',
        'Bulgarian Bible (BULG)': 'BULG',
        'Bulgarian New Testament: Easy-to-Read Version (ERV-BG)': 'ERV-BG',
        'Библия, нов превод от оригиналните езици (с неканоничните книги) (CBT)': 'CBT',
        'Библия, синодално издание (BOB)': 'BOB',
        'Библия, ревизирано издание (BPB)': 'BPB',
        'Chinanteco de Comaltepec (CCO)': 'CCO',
        'Ang Pulong Sa Dios (APSD-CEB)': 'APSD-CEB',
        'Cherokee New Testament (CHR)': 'CHR',
        'Kurdi Sorani Standard (KSS)': 'KSS',
        'Cakchiquel Occidental (CKW)': 'CKW',
        'Bible 21 (B21)': 'B21',
        'Slovo na cestu (SNC)': 'SNC',
        'Beibl William Morgan (BWM)': 'BWM',
        'Bibelen på hverdagsdansk (BPH)': 'BPH',
        'Dette er Biblen på dansk (DN1933)': 'DN1933',
        'Hoffnung für Alle (HOF)': 'HOF',
        'Luther Bibel 1545 (LUTH1545)': 'LUTH1545',
        'Neue Genfer Übersetzung (NGU-DE)': 'NGU-DE',
        'Schlachter 1951 (SCH1951)': 'SCH1951',
        'Schlachter 2000 (SCH2000)': 'SCH2000',
        '21st Century King James Version (KJ21)': 'KJ21',
        'American Standard Version (ASV)': 'ASV',
        'Amplified Bible (AMP)': 'AMP',
        'Amplified Bible, Classic Edition (AMPC)': 'AMPC',
        'BRG Bible (BRG)': 'BRG',
        'Christian Standard Bible (CSB)': 'CSB',
        'Common English Bible (CEB)': 'CEB',
        'Complete Jewish Bible (CJB)': 'CJB',
        'Contemporary English Version (CEV)': 'CEV',
        'Darby Translation (DARBY)': 'DARBY',
        'Disciples’ Literal New Testament (DLNT)': 'DLNT',
        'Douay-Rheims 1899 American Edition (DRA)': 'DRA',
        'Easy-to-Read Version (ERV)': 'ERV',
        'EasyEnglish Bible (EASY)': 'EASY',
        'Evangelical Heritage Version (EHV)': 'EHV',
        'English Standard Version (ESV)': 'ESV',
        'English Standard Version Anglicised (ESVUK)': 'ESVUK',
        'Expanded Bible (EXB)': 'EXB',
        '1599 Geneva Bible (GNV)': 'GNV',
        'GOD’S WORD Translation (GW)': 'GW',
        'Good News Translation (GNT)': 'GNT',
        'Holman Christian Standard Bible (HCSB)': 'HCSB',
        'International Children’s Bible (ICB)': 'ICB',
        'International Standard Version (ISV)': 'ISV',
        'J.B. Phillips New Testament (PHILLIPS)': 'PHILLIPS',
        'Jubilee Bible 2000 (JUB)': 'JUB',
        'King James Version (KJV)': 'KJV',
        'Authorized (King James) Version (AKJV)': 'AKJV',
        'Legacy Standard Bible (LSB)': 'LSB',
        'Lexham English Bible (LEB)': 'LEB',
        'Living Bible (TLB)': 'TLB',
        'The Message (MSG)': 'MSG',
        'Modern English Version (MEV)': 'MEV',
        'Mounce Reverse Interlinear New Testament (MOUNCE)': 'MOUNCE',
        'Names of God Bible (NOG)': 'NOG',
        'New American Bible (Revised Edition) (NABRE)': 'NABRE',
        'New American Standard Bible (NASB)': 'NASB',
        'New American Standard Bible 1995 (NASB1995)': 'NASB1995',
        'New Catholic Bible (NCB)': 'NCB',
        'New Century Version (NCV)': 'NCV',
        'New English Translation (NET)': 'NET',
        'New International Reader\'s Version (NIRV)': 'NIRV',
        'New International Version (NIV)': 'NIV',
        'New International Version - UK (NIVUK)': 'NIVUK',
        'New King James Version (NKJV)': 'NKJV',
        'New Life Version (NLV)': 'NLV',
        'New Living Translation (NLT)': 'NLT',
        'New Matthew Bible (NMB)': 'NMB',
        'New Revised Standard Version, Anglicised (NRSVA)': 'NRSVA',
        'New Revised Standard Version, Anglicised Catholic Edition (NRSVACE)': 'NRSVACE',
        'New Revised Standard Version Catholic Edition (NRSVCE)': 'NRSVCE',
        'New Revised Standard Version Updated Edition (NRSVUE)': 'NRSVUE',
        'New Testament for Everyone (NTFE)': 'NTFE',
        'Orthodox Jewish Bible (OJB)': 'OJB',
        'Revised Geneva Translation (RGT)': 'RGT',
        'Revised Standard Version (RSV)': 'RSV',
        'Revised Standard Version Catholic Edition (RSVCE)': 'RSVCE',
        'Tree of Life Version (TLV)': 'TLV',
        'The Voice (VOICE)': 'VOICE',
        'World English Bible (WEB)': 'WEB',
        'Worldwide English (New Testament) (WE)': 'WE',
        'Wycliffe Bible (WYC)': 'WYC',
        'Young\'s Literal Translation (YLT)': 'YLT',
        'La Biblia de las Américas (LBLA)': 'LBLA',
        'Biblia del Jubileo (JBS)': 'JBS',
        'Dios Habla Hoy (DHH)': 'DHH',
        'Nueva Biblia de las Américas (NBLA)': 'NBLA',
        'Nueva Biblia Viva (NBV)': 'NBV',
        'Nueva Traducción Viviente (NTV)': 'NTV',
        'Nueva Versión Internacional (NVI)': 'NVI',
        'Nueva Versión Internacional (Castilian) (CST)': 'CST',
        'Palabra de Dios para Todos (PDT)': 'PDT',
        'La Palabra (España) (BLP)': 'BLP',
        'La Palabra (Hispanoamérica) (BLPH)': 'BLPH',
        'Reina Valera Actualizada (RVA-2015)': 'RVA-2015',
        'Reina Valera Contemporánea (RVC)': 'RVC',
        'Reina-Valera 1960 (RVR1960)': 'RVR1960',
        'Reina Valera Revisada (RVR1977)': 'RVR1977',
        'Reina-Valera 1995 (RVR1995)': 'RVR1995',
        'Reina-Valera Antigua (RVA)': 'RVA',
        'Spanish Blue Red and Gold Letter Edition (SRV-BRG)': 'SRV-BRG',
        'Traducción en lenguaje actual (TLA)': 'TLA',
        'Raamattu 1933/38 (R1933)': 'R1933',
        'La Bible du Semeur (BDS)': 'BDS',
        'Louis Segond (LSG)': 'LSG',
        'Nouvelle Edition de Genève – NEG1979 (NEG1979)': 'NEG1979',
        'Segond 21 (SG21)': 'SG21',
        '1550 Stephanus New Testament (TR1550)': 'TR1550',
        '1881 Westcott-Hort New Testament (WHNU)': 'WHNU',
        '1894 Scrivener New Testament (TR1894)': 'TR1894',
        'SBL Greek New Testament (SBLGNT)': 'SBLGNT',
        'Tyndale House Greek New Testament (THGNT)': 'THGNT',
        'Gujarati: પવિત્ર બાઈબલ (GERV)': 'GERV',
        'Habrit Hakhadasha/Haderekh (HHH)': 'HHH',
        'The Westminster Leningrad Codex (WLC)': 'WLC',
        'Hindi Bible: Easy-to-Read Version (ERV-HI)': 'ERV-HI',
        'Saral Hindi Bible (SHB)': 'SHB',
        'Ang Pulong Sang Dios (HLGN)': 'HLGN',
        'New Chhattisgarhi Translation (नवां नियम छत्तीसगढ़ी) (NCA)': 'NCA',
        'Biblija: suvremeni hrvatski prijevod (SHP)': 'SHP',
        'Hrvatski Novi Zavjet – Rijeka 2001 (HNZ-RI)': 'HNZ-RI',
        'Knijga O Kristu (CRO)': 'CRO',
        'Haitian Creole Version (HCV)': 'HCV',
        'Nouvo Testaman: Vèsyon Kreyòl Fasil (VKF)': 'VKF',
        'Hungarian Károli (KAR)': 'KAR',
        'Hungarian Bible: Easy-to-Read Version (ERV-HU)': 'ERV-HU',
        'Hungarian New Translation (NT-HU)': 'NT-HU',
        'Hawai‘i Pidgin (HWP)': 'HWP',
        'Icelandic Bible (ICELAND)': 'ICELAND',
        'La Bibbia della Gioia (BDG)': 'BDG',
        'Conferenza Episcopale Italiana (CEI)': 'CEI',
        'La Nuova Diodati (LND)': 'LND',
        'Nuova Riveduta 1994 (NR1994)': 'NR1994',
        'Nuova Riveduta 2006 (NR2006)': 'NR2006',
        'Japanese Living Bible (JLB)': 'JLB',
        'Jacalteco, Oriental (JAC)': 'JAC',
        'Kekchi (KEK)': 'KEK',
        'Korean Living Bible (KLB)': 'KLB',
        'Biblia Sacra Vulgata (VULGATE)': 'VULGATE',
        'Endagaano Enkadde nʼEndagaano Empya (LCB)': 'LCB',
        'Maori Bible (MAORI)': 'MAORI',
        'Macedonian New Testament (MNT)': 'MNT',
        'Marathi Bible: Easy-to-Read Version (ERV-MR)': 'ERV-MR',
        'Mam, Central (MVC)': 'MVC',
        'Mam de Todos Santos Chuchumatán (MVJ)': 'MVJ',
        'Reimer 2001 (REIMER)': 'REIMER',
        'Nepali Bible: Easy-to-Read Version (ERV-NE)': 'ERV-NE',
        'Náhuatl de Guerrero (NGU)': 'NGU',
        'BasisBijbel (BB)': 'BB',
        'Het Boek (HTB)': 'HTB',
        'Det Norsk Bibelselskap 1930 (DNB1930)': 'DNB1930',
        'En Levende Bok (LB)': 'LB',
        'Mawu a Mulungu mu Chichewa Chalero (CCL)': 'CCL',
        'Oriya Bible: Easy-to-Read Version (ERV-OR)': 'ERV-OR',
        'Punjabi Bible: Easy-to-Read Version (ERV-PA)': 'ERV-PA',
        'Nowe Przymierze (NP)': 'NP',
        'Słowo Życia (SZ-PL)': 'SZ-PL',
        'Updated Gdańsk Bible (UBG)': 'UBG',
        'Ne Bibliaj Tik Nawat (NBTN)': 'NBTN',
        'Almeida Revista e Corrigida 2009 (ARC)': 'ARC',
        'Portuguese New Testament: Easy-to-Read Version (VFL)': 'VFL',
        'Nova Traduҫão na Linguagem de Hoje 2000 (NTLH)': 'NTLH',
        'Nova Versão Transformadora (NVT)': 'NVT',
        'Nova Versão Internacional (NVI-PT)': 'NVI-PT',
        'O Livro (OL)': 'OL',
        'Mushuj Testamento Diospaj Shimi (MTDS)': 'MTDS',
        'Quiché, Centro Occidental (QUT)': 'QUT',
        'Cornilescu 1924 - Revised 2010, 2014 (RMNN)': 'RMNN',
        'Nouă Traducere În Limba Română (NTLR)': 'NTLR',
        'New Russian Translation (NRT)': 'NRT',
        'Священное Писание (Восточный Перевод) (CARS)': 'CARS',
        'Священное Писание (Восточный перевод), версия для Таджикистана (CARST)': 'CARST',
        'Священное Писание (Восточный перевод), версия с «Аллахом» (CARSA)': 'CARSA',
        'Russian New Testament: Easy-to-Read Version (ERV-RU)': 'ERV-RU',
        'Russian Synodal Version (RUSV)': 'RUSV',
        'Nádej pre kazdého (NPK)': 'NPK',
        'Somali Bible (SOM)': 'SOM',
        'Albanian Bible (ALB)': 'ALB',
        'New Serbian Translation (NSP)': 'NSP',
        'Serbian New Testament: Easy-to-Read Version (ERV-SR)': 'ERV-SR',
        'nuBibeln (Swedish Contemporary Bible) (NUB)': 'NUB',
        'Svenska 1917 (SV1917)': 'SV1917',
        'Svenska Folkbibeln (SFB)': 'SFB',
        'Svenska Folkbibeln 2015 (SFB15)': 'SFB15',
        'Swedish New Living Bible (Nya Levande Bibeln) (SVL)': 'SVL',
        'Agano Jipya: Tafsiri ya Kusoma-Kwa-Urahisi (TKU)': 'TKU',
        'Neno: Bibilia Takatifu (SNT)': 'SNT',
        'Tamil Bible: Easy-to-Read Version (ERV-TA)': 'ERV-TA',
        'New Thai Version (NTV-BIBLE)': 'NTV-BIBLE',
        'Thai New Testament: Easy-to-Read Version (ERV-TH)': 'ERV-TH',
        'Thai New Contemporary Bible (TNCV)': 'TNCV',
        'Ang Bagong Tipan: Filipino Standard Version (FSV)': 'FSV',
        'Ang Biblia (1978) (ABTAG1978)': 'ABTAG1978',
        'Ang Biblia, 2001 (ABTAG2001)': 'ABTAG2001',
        'Ang Dating Biblia (1905) (ADB1905)': 'ADB1905',
        'Ang Salita ng Diyos (SND)': 'SND',
        'Ang Salita ng Dios (Tagalog Contemporary Bible) (ASND)': 'ASND',
        'Magandang Balita Biblia (MBBTAG)': 'MBBTAG',
        'Magandang Balita Biblia (with Deuterocanon) (MBBTAG-DC)': 'MBBTAG-DC',
        'Nkwa Asem (NA-TWI)': 'NA-TWI',
        'Ukrainian Bible (UKR)': 'UKR',
        'Ukrainian New Testament: Easy-to-Read Version (ERV-UK)': 'ERV-UK',
        'Urdu Bible: Easy-to-Read Version (ERV-UR)': 'ERV-UR',
        'Uspanteco (USP)': 'USP',
        'Bản Dịch 2011 (BD2011)': 'BD2011',
        'New Vietnamese Bible (NVB)': 'NVB',
        'Vietnamese Bible: Easy-to-Read Version (BPT)': 'BPT',
        'Bíbélì Mímọ́ Yorùbá Òde Òn (BYO)': 'BYO',
        'Chinese Contemporary Bible (Simplified) (CCB)': 'CCB',
        'Chinese Contemporary Bible (Traditional) (CCBT)': 'CCBT',
        'Chinese New Testament: Easy-to-Read Version (ERV-ZH)': 'ERV-ZH',
        'Chinese New Version (Simplified) (CNVS)': 'CNVS',
        'Chinese New Version (Traditional) (CNVT)': 'CNVT',
        'Chinese Standard Bible (Simplified) (CSBS)': 'CSBS',
        'Chinese Standard Bible (Traditional) (CSBT)': 'CSBT',
        'Chinese Union Version (Simplified) (CUVS)': 'CUVS',
        'Chinese Union Version (Traditional) (CUV)': 'CUV',
        'Chinese Union Version Modern Punctuation (Simplified) (CUVMPS)': 'CUVMPS',
        'Chinese Union Version Modern Punctuation (Traditional) (CUVMPT)': 'CUVMPT',
        'Revised Chinese Union Version (Simplified Script) Shen Edition (RCU17SS)': 'RCU17SS',
        'Revised Chinese Union Version (Traditional Script) Shen Edition (RCU17TS)': 'RCU17TS'
    }

    QURAN = {
        '(Afar) Sheikh Mahmoud Abdel Qader Hamz And Group Of Scholars': 'aar-sheikhmahmoudab',
        '(Achinese) Tgk. H. Mahjiddin Jusuf': 'ace-tgkhmahjiddinju',
        '(Afrikaans) Imam M. A. Baker': 'afr-imammabaker',
        '(Amharic) Muhammed Sadiq And Muhammed Sani Habib (Latin roman script version)': 'amh-muhammedsadiqan-la',
        '(Amharic) Muhammed Sadiq And Muhammed Sani Habib (Latin roman script version with diacritical marks)': 'amh-muhammedsadiqan-lad',
        '(Amharic) Muhammed Sadiq And Muhammed Sani Habib': 'amh-muhammedsadiqan',
        '(Arabic) Jalal Ad Din Al Mahalli And Jalal Ad Din As Suyuti': 'ara-jalaladdinalmah',
        '(Arabic) King Fahad Quran Complex (Latin roman script version)': 'ara-kingfahadquranc-la',
        '(Arabic) King Fahad Quran Complex': 'ara-kingfahadquranc',
        '(Arabic) Quran Transliteration (Latin roman script version)': 'ara-quran-la',
        '(Arabic) Quran Transliteration (Latin roman script version) 2': 'ara-quran-la1',
        '(Arabic) Quran Transliteration (Latin roman script version) 3': 'ara-quran-la2',
        '(Arabic) Quran Transliteration (Latin roman script version) 4': 'ara-quran-la3',
        '(Arabic) Quran Transliteration (Latin roman script version) 5': 'ara-quran-la4',
        '(Arabic) Quran Transliteration (Latin roman script version) 6': 'ara-quran-la5',
        '(Arabic) Quran Transliteration (Latin roman script version with diacritical marks)': 'ara-quran-lad4',
        '(Arabic) Quran Academy': 'ara-quranacademy',
        '(Arabic) Quran Bazzi': 'ara-quranbazzi',
        '(Arabic) Quran Doori': 'ara-qurandoori',
        '(Arabic) Quran Doori Non Unicode': 'ara-qurandoorinonun',
        '(Arabic) Quran Indopak': 'ara-quranindopak',
        '(Arabic) Quran Khaled Hosney': 'ara-qurankhaledhosn',
        '(Arabic) Quran Nastaleeq Non Unicode': 'ara-qurannastaleeqn',
        '(Arabic) Quran Phonetics Transliteration (Latin roman script version)': 'ara-quranphoneticst-la',
        '(Arabic) Quran Phonetics Transliteration': 'ara-quranphoneticst',
        '(Arabic) Quran Qaloon': 'ara-quranqaloon',
        '(Arabic) Quran Qumbul': 'ara-quranqumbul',
        '(Arabic) Quran Shouba': 'ara-quranshouba',
        '(Arabic) Quran Simple': 'ara-quransimple',
        '(Arabic) Quran Soosi': 'ara-quransoosi',
        '(Arabic) Quran Soosi Non Unicode': 'ara-quransoosinonun',
        '(Arabic) Quran Uthmani Enc': 'ara-quranuthmanienc',
        '(Arabic) Quran Uthmani Hafs': 'ara-quranuthmanihaf',
        '(Arabic) Quran Uthmani Hafs No Diacritics': 'ara-quranuthmanihaf1',
        '(Arabic) Quran Warsh': 'ara-quranwarsh',
        '(Arabic) Siraj Tafseer': 'ara-sirajtafseer',
        '(Arabic) Siraj Tafseer No Diacritics': 'ara-sirajtafseernod',
        '(Assamese) Shaykh Rafeequl Islam Habibur Rahman (Latin roman script version)': 'asm-shaykhrafeequli-la',
        '(Assamese) Shaykh Rafeequl Islam Habibur Rahman (Latin roman script version with diacritical marks)': 'asm-shaykhrafeequli-lad',
        '(Assamese) Shaykh Rafeequl Islam Habibur Rahman': 'asm-shaykhrafeequli',
        '(Azerbaijani) Alikhan Musayev (Latin roman script version)': 'aze-alikhanmusayev-la',
        '(Azerbaijani) Alikhan Musayev': 'aze-alikhanmusayev',
        '(Azerbaijani) Khan Musayev (Latin roman script version)': 'aze-khanmusayev-la',
        '(Azerbaijani) Khan Musayev': 'aze-khanmusayev',
        '(Azerbaijani) Vasim Mammadaliyev And Ziya Bunyadov (Latin roman script version)': 'aze-vasimmammadaliy-la',
        '(Azerbaijani) Vasim Mammadaliyev And Ziya Bunyadov': 'aze-vasimmammadaliy',
        '(Bambara) Deen Muhammad': 'bam-deenmuhammad',
        '(Bambara) Fodi Suliman Kanti': 'bam-fodisulimankant',
        '(Bambara) Karamo Baba Mamadi Jani': 'bam-karamobabamamad',
        '(Bengali) Abu Bakr Zakaria (Latin roman script version)': 'ben-abubakrzakaria-la',
        '(Bengali) Abu Bakr Zakaria (Latin roman script version with diacritical marks)': 'ben-abubakrzakaria-lad',
        '(Bengali) Abu Bakr Zakaria': 'ben-abubakrzakaria',
        '(Bengali) Muhiuddin Khan (Latin roman script version)': 'ben-muhiuddinkhan-la',
        '(Bengali) Muhiuddin Khan (Latin roman script version with diacritical marks)': 'ben-muhiuddinkhan-lad',
        '(Bengali) Muhiuddin Khan': 'ben-muhiuddinkhan',
        '(Bengali) Zohurul Hoque (Latin roman script version)': 'ben-zohurulhoque-la',
        '(Bengali) Zohurul Hoque (Latin roman script version with diacritical marks)': 'ben-zohurulhoque-lad',
        '(Bengali) Zohurul Hoque': 'ben-zohurulhoque',
        '(Berber) Ramdane At Mansour (Latin roman script version)': 'ber-ramdaneatmansou-la',
        '(Berber) Ramdane At Mansour': 'ber-ramdaneatmansou',
        '(Bosnian) Besim Korkut (Latin roman script version)': 'bos-besimkorkut-la',
        '(Bosnian) Besim Korkut': 'bos-besimkorkut',
        '(Bosnian) Korkut (Latin roman script version)': 'bos-korkut-la',
        '(Bosnian) Korkut': 'bos-korkut',
        '(Bosnian) Muhamed Mehanovic (Latin roman script version)': 'bos-muhamedmehanovi-la',
        '(Bosnian) Muhamed Mehanovic': 'bos-muhamedmehanovi',
        '(Bosnian) Mustafa Mlivo (Latin roman script version)': 'bos-mustafamlivo-la',
        '(Bosnian) Mustafa Mlivo': 'bos-mustafamlivo',
        '(Bosnian) Transliterim': 'bos-transliterim',
        '(Bosnian) Www.islamhouse.com (Latin roman script version)': 'bos-wwwislamhouseco-la',
        '(Bosnian) Www.islamhouse.com': 'bos-wwwislamhouseco',
        '(Bulgarian) Tzvetan Theophanov (Latin roman script version)': 'bul-tzvetantheophan-la',
        '(Bulgarian) Tzvetan Theophanov (Latin roman script version with diacritical marks)': 'bul-tzvetantheophan-lad',
        '(Bulgarian) Tzvetan Theophanov': 'bul-tzvetantheophan',
        '(Catalan) Youssef Lyoussi (Latin roman script version)': 'cat-yousseflyoussi-la',
        '(Catalan) Youssef Lyoussi': 'cat-yousseflyoussi',
        '(Czech) A. R. Nykl (Latin roman script version)': 'ces-arnykl-la',
        '(Czech) A. R. Nykl': 'ces-arnykl',
        '(Czech) Hadi Abdollahian (Latin roman script version)': 'ces-hadiabdollahian-la',
        '(Czech) Hadi Abdollahian': 'ces-hadiabdollahian',
        '(Czech) Preklad I. Hrbek (Latin roman script version)': 'ces-prekladihrbek-la',
        '(Czech) Preklad I. Hrbek': 'ces-prekladihrbek',
        '(Dagbani) Muhammad Baba Ghtobo': 'dag-muhammadbabaght',
        '(Danish) Hadi Abdollahian': 'dan-hadiabdollahian',
        '(Danish) Van De Taal': 'dan-vandetaal',
        '(German) Abu Rida Muhammad Ibn Ahmad Ibn Rassoul (Latin roman script version)': 'deu-aburidamuhammad-la',
        '(German) Abu Rida Muhammad Ibn Ahmad Ibn Rassoul': 'deu-aburidamuhammad',
        '(German) Adel Theodor Khoury (Latin roman script version)': 'deu-adeltheodorkhou-la',
        '(German) Adel Theodor Khoury': 'deu-adeltheodorkhou',
        '(German) Amir Zaidan (Latin roman script version)': 'deu-amirzaidan-la',
        '(German) Amir Zaidan': 'deu-amirzaidan',
        '(German) A. S. F. Bubenheim And N. Elyas (Latin roman script version)': 'deu-asfbubenheimand-la',
        '(German) A. S. F. Bubenheim And N. Elyas': 'deu-asfbubenheimand',
        '(German) Frank Bubenheim And Nadeem Elyas (Latin roman script version)': 'deu-frankbubenheima-la',
        '(German) Frank Bubenheim And Nadeem Elyas': 'deu-frankbubenheima',
        '(Divehi) Office Of The President Of Maldives': 'div-officeofthepres',
        '(English) Abdel Haleem': 'eng-abdelhaleem',
        '(English) Abdul Hye': 'eng-abdulhye',
        '(English) Abdullah Yusuf Ali': 'eng-abdullahyusufal',
        '(English) Abdul Majid Daryabadi': 'eng-abdulmajiddarya',
        '(English) Abul Ala Maududi': 'eng-abulalamaududi',
        '(English) Ahmed Ali': 'eng-ahmedali',
        '(English) Aisha Bewley': 'eng-aishabewley',
        '(English) A. J. Arberry': 'eng-ajarberry',
        '(English) Al Bilal Muhammad Et Al': 'eng-albilalmuhammad',
        '(English) Ali Bakhtiari Nejad': 'eng-alibakhtiarinej',
        '(English) Ali Quli Qarai': 'eng-aliquliqarai',
        '(English) Ali Quli Qarai 2': 'eng-aliquliqarai1',
        '(English) Ali Unal': 'eng-aliunal',
        '(English) Almuntakhab Fi Tafsir Alquran Alkarim': 'eng-almuntakhabfita',
        '(English) Dr Kamal Omar': 'eng-drkamalomar',
        '(English) Dr Laleh Bakhtiar': 'eng-drlalehbakhtiar',
        '(English) Dr Munir Munshey': 'eng-drmunirmunshey',
        '(English) Edward Henry Palmer': 'eng-edwardhenrypalm',
        '(English) Farook Malik': 'eng-farookmalik',
        '(English) George Sale': 'eng-georgesale',
        '(English) Hamid S Aziz': 'eng-hamidsaziz',
        '(English) John Medows Rodwell': 'eng-johnmedowsrodwe',
        '(English) Literal': 'eng-literal',
        '(English) Maududi': 'eng-maududi',
        '(English) Mir Anees Original': 'eng-miraneesorigina',
        '(English) Mir Aneesuddin': 'eng-miraneesuddin',
        '(English) Mohammad Habib Shakir': 'eng-mohammadhabibsh',
        '(English) Mohammad Shafi': 'eng-mohammadshafi',
        '(English) Mohammed Marmaduke William Pickthall': 'eng-mohammedmarmadu',
        '(English) Mufti Taqi Usmani': 'eng-muftitaqiusmani',
        '(English) Muhammad Asad': 'eng-muhammadasad',
        '(English) Muhammad Mahmoud Ghali': 'eng-muhammadmahmoud',
        '(English) Muhammad Sarwar': 'eng-muhammadsarwar',
        '(English) Muhammad Taqi Ud Din Al Hilali And Muhammad Muhsin Khan': 'eng-muhammadtaqiudd',
        '(English) Muhammad Taqi Usmani': 'eng-muhammadtaqiusm',
        '(English) Mustafa Khattab Allah Edition': 'eng-mustafakhattaba',
        '(English) Mustafa Khattab God Edition': 'eng-mustafakhattabg',
        '(English) N J Dawood': 'eng-njdawood',
        '(English) Rowwad Translation Center': 'eng-rowwadtranslati',
        '(English) Safi Kaskas': 'eng-safikaskas',
        '(English) Safi Ur Rahman Al Mubarakpuri': 'eng-safiurrahmanalm',
        '(English) Shabbir Ahmed': 'eng-shabbirahmed',
        '(English) Syed Vickar Ahamed': 'eng-syedvickarahame',
        '(English) Talal A Itani New Translation': 'eng-talalaitaninewt',
        '(English) Talal Itani': 'eng-talalitani',
        '(English) Tbirving': 'eng-tbirving',
        '(English) The Monotheist Group Edition': 'eng-themonotheistgr',
        '(English) The Monotheist Group Edition 2': 'eng-themonotheistgr1',
        '(English) The Study Quran': 'eng-thestudyquran',
        '(English) Umm Muhammad': 'eng-ummmuhammad',
        '(English) Wahiduddin Khan': 'eng-wahiduddinkhan',
        '(English) Yusuf Ali Orig': 'eng-yusufaliorig',
        '(Esperanto) Hadi Abdollahian': 'epo-hadiabdollahian',
        '(Persian) Abdolmohammad Ayati': 'fas-abdolmohammaday',
        '(Persian) Abolfazl Bahrampour': 'fas-abolfazlbahramp',
        '(Persian) Baha Oddin Khorramshahi': 'fas-bahaoddinkhorra',
        '(Persian) Dr. Hussien Tagi': 'fas-drhussientagi',
        '(Persian) Hussain Ansarian': 'fas-hussainansarian',
        '(Persian) Islamhouse.com Persian Team': 'fas-islamhousecompe',
        '(Persian) Mahdi Elahi Ghomshei': 'fas-mahdielahighoms',
        '(Persian) Mohammad Kazem Moezzi': 'fas-mohammadkazemmo',
        '(Persian) Mohammad Mahdi Fooladvand': 'fas-mohammadmahdifo',
        '(Persian) Mohammad Sadeqi Tehrani': 'fas-mohammadsadeqit',
        '(Persian) Mohsen Gharaati': 'fas-mohsengharaati',
        '(Persian) Mostafa Khorramdel': 'fas-mostafakhorramd',
        '(Persian) Naser Makarem Shirazi': 'fas-nasermakaremshi',
        '(Persian) Sayyed Jalaloddin Mojtabavi': 'fas-sayyedjalaloddi',
        '(Persian) Unknown': 'fas-unknown',
        '(Filipino) Abdullatif Eduardo M. Arceo': 'fil-abdullatifeduar',
        '(Filipino) Www.islamhouse.com': 'fil-wwwislamhouseco',
        '(Finnish) Unknown (Latin roman script version)': 'fin-unknown-la',
        '(Finnish) Unknown': 'fin-unknown',
        '(French) Islamic Foundation (Latin roman script version)': 'fra-islamicfoundati-la',
        '(French) Islamic Foundation': 'fra-islamicfoundati',
        '(French) Muhammad Hameedullah (Latin roman script version)': 'fra-muhammadhameedu-la',
        '(French) Muhammad Hameedullah': 'fra-muhammadhameedu',
        '(French) Muhammad Hamidullah (Latin roman script version)': 'fra-muhammadhamidul-la',
        '(French) Muhammad Hamidullah': 'fra-muhammadhamidul',
        '(French) Rashid Maash (Latin roman script version)': 'fra-rashidmaash-la',
        '(French) Rashid Maash': 'fra-rashidmaash',
        '(French) Shahnaz Saidi Benbetka (Latin roman script version)': 'fra-shahnazsaidiben-la',
        '(French) Shahnaz Saidi Benbetka': 'fra-shahnazsaidiben',
        '(Fulah) Rowad Translation Center And Islamhouse': 'ful-rowadtranslatio',
        '(Gujarati) Rabila Al Omari (Latin roman script version)': 'guj-rabilaalomari-la',
        '(Gujarati) Rabila Al Omari (Latin roman script version with diacritical marks)': 'guj-rabilaalomari-lad',
        '(Gujarati) Rabila Al Omari': 'guj-rabilaalomari',
        '(Hausa) Abubakar Mahmood Jummi (Latin roman script version)': 'hau-abubakarmahmood-la',
        '(Hausa) Abubakar Mahmood Jummi': 'hau-abubakarmahmood',
        '(Hausa) Abubakar Mahmoud Gumi (Latin roman script version)': 'hau-abubakarmahmoud-la',
        '(Hausa) Abubakar Mahmoud Gumi': 'hau-abubakarmahmoud',
        '(Hebrew) Darusalam House In Jerusalem': 'heb-darusalamhousei',
        '(Hebrew) Unknown': 'heb-unknown',
        '(Hindi) Maulana Azizul Haque Al Umari (Latin roman script version)': 'hin-maulanaazizulha-la',
        '(Hindi) Maulana Azizul Haque Al Umari': 'hin-maulanaazizulha',
        '(Hindi) Muhammad Farooq Khan And Muhammad Ahmed (Latin roman script version)': 'hin-muhammadfarooqk-la',
        '(Hindi) Muhammad Farooq Khan And Muhammad Ahmed': 'hin-muhammadfarooqk',
        '(Hindi) Suhel Farooq Khan And Saifur Rahman Nadwi (Latin roman script version)': 'hin-suhelfarooqkhan-la',
        '(Hindi) Suhel Farooq Khan And Saifur Rahman Nadwi': 'hin-suhelfarooqkhan',
        '(Croatian) Unknown (Latin roman script version)': 'hrv-unknown-la',
        '(Croatian) Unknown': 'hrv-unknown',
        '(Hungarian) Dr. Ahmed Abdel Rahman Okfat Tashaab (Latin roman script version)': 'hun-drahmedabdelrah-la',
        '(Hungarian) Dr. Ahmed Abdel Rahman Okfat Tashaab': 'hun-drahmedabdelrah',
        '(Iranun) Abdul Aziz Gro Aalem Saromintang': 'ilp-abdulazizgroaal',
        '(Indonesian) Indonesian Islamic Affairs Ministry': 'ind-indonesianislam',
        '(Indonesian) Jalal Ad Din Al Mahalli And Jalal Ad Din As Suyuti': 'ind-jalaladdinalmah',
        '(Indonesian) King Fahd Complex': 'ind-kingfahdcomplex',
        '(Indonesian) Muhammad Quraish Shihab Et Al.': 'ind-muhammadquraish',
        '(Indonesian) The Sabiq Company': 'ind-thesabiqcompany',
        '(Indonesian) Unknown': 'ind-unknown',
        '(Italian) Hamza Roberto Piccardo (Latin roman script version)': 'ita-hamzarobertopic-la',
        '(Italian) Hamza Roberto Piccardo': 'ita-hamzarobertopic',
        '(Javanese) Unknown (Latin roman script version)': 'jav-unknown-la',
        '(Javanese) Unknown': 'jav-unknown',
        '(Japanese) Ryoichi Mita (Latin roman script version)': 'jpn-ryoichimita-la',
        '(Japanese) Ryoichi Mita (Latin roman script version with diacritical marks)': 'jpn-ryoichimita-lad',
        '(Japanese) Ryoichi Mita': 'jpn-ryoichimita',
        '(Kannada) Abdussalam Puthige (Latin roman script version)': 'kan-abdussalamputhi-la',
        '(Kannada) Abdussalam Puthige (Latin roman script version with diacritical marks)': 'kan-abdussalamputhi-lad',
        '(Kannada) Abdussalam Puthige': 'kan-abdussalamputhi',
        '(Kazakh) Khalifah Altai (Latin roman script version)': 'kaz-khalifahaltai-la',
        '(Kazakh) Khalifah Altai (Latin roman script version with diacritical marks)': 'kaz-khalifahaltai-lad',
        '(Kazakh) Khalifah Altai': 'kaz-khalifahaltai',
        '(Kazakh) Khalifah Altai Charity Foundation (Latin roman script version)': 'kaz-khalifahaltaich-la',
        '(Kazakh) Khalifah Altai Charity Foundation (Latin roman script version with diacritical marks)': 'kaz-khalifahaltaich-lad',
        '(Kazakh) Khalifah Altai Charity Foundation': 'kaz-khalifahaltaich',
        '(Khmer) Cambodian Muslim Community Development (Latin roman script version)': 'khm-cambodianmuslim-la',
        '(Khmer) Cambodian Muslim Community Development': 'khm-cambodianmuslim',
        '(Kinyarwanda) R. M. C. Rwanda': 'kin-rmcrwanda',
        '(Kinyarwanda) Rwanda Muslims Association Team': 'kin-rwandamuslimsas',
        '(Kirghiz) Shams Al Din Hakimov (Latin roman script version)': 'kir-shamsaldinhakim-la',
        '(Kirghiz) Shams Al Din Hakimov (Latin roman script version with diacritical marks)': 'kir-shamsaldinhakim-lad',
        '(Kirghiz) Shams Al Din Hakimov': 'kir-shamsaldinhakim',
        '(Kurmanji) Unknown (Latin roman script version)': 'kmr-unknown-la',
        '(Kurmanji) Unknown': 'kmr-unknown',
        '(Kendayan) Unknown': 'knx-unknown',
        '(Korean) Hamid Choi (Latin roman script version)': 'kor-hamidchoi-la',
        '(Korean) Hamid Choi': 'kor-hamidchoi',
        '(Korean) Unknown (Latin roman script version)': 'kor-unknown-la',
        '(Korean) Unknown': 'kor-unknown',
        '(Kurdish) Burhan Muhammad Amin': 'kur-burhanmuhammada',
        '(Kurdish) Muhammad Saleh Bamoki': 'kur-muhammadsalehba',
        '(Latin) Hadi Abdollahian': 'lat-hadiabdollahian',
        '(Lingala) Zakariya Muhammed Balingongo': 'lin-zakariyamuhamme',
        '(Ganda) Fareeq Musa': 'lug-fareeqmusa',
        '(Luyia) Mohammad Ramadhan Sebwa, Ramadhan Hajj Ndeka, Ismail Were, Musa Murasi Salim Kukuya, Yusuf Shiundu Malala, Yahya Wafula Ojwang, Haroon Albert Msah': 'luy-mohammadramadha',
        '(Malayalam) Abdul Hameed Madani And Kunhi Mohammed (Latin roman script version)': 'mal-abdulhameedmada-la',
        '(Malayalam) Abdul Hameed Madani And Kunhi Mohammed (Latin roman script version with diacritical marks)': 'mal-abdulhameedmada-lad',
        '(Malayalam) Abdul Hameed Madani And Kunhi Mohammed': 'mal-abdulhameedmada',
        '(Malayalam) Cheriyamundam Abdul Hameed And Kunhi Mohammed Parappoor (Latin roman script version)': 'mal-cheriyamundamab-la',
        '(Malayalam) Cheriyamundam Abdul Hameed And Kunhi Mohammed Parappoor (Latin roman script version with diacritical marks)': 'mal-cheriyamundamab-lad',
        '(Malayalam) Cheriyamundam Abdul Hameed And Kunhi Mohammed Parappoor': 'mal-cheriyamundamab',
        '(Malayalam) Muhammad Karakunnu And Vanidas Elayavoor (Latin roman script version)': 'mal-muhammadkarakun-la',
        '(Malayalam) Muhammad Karakunnu And Vanidas Elayavoor (Latin roman script version with diacritical marks)': 'mal-muhammadkarakun-lad',
        '(Malayalam) Muhammad Karakunnu And Vanidas Elayavoor': 'mal-muhammadkarakun',
        '(Marathi) Muhammad Shafi I Ansari (Latin roman script version)': 'mar-muhammadshafiia-la',
        '(Marathi) Muhammad Shafi I Ansari (Latin roman script version with diacritical marks)': 'mar-muhammadshafiia-lad',
        '(Marathi) Muhammad Shafi I Ansari': 'mar-muhammadshafiia',
        '(Macedonian) Macedonian Scholars': 'mkd-macedonianschol',
        '(Macedonian) Sheikh Hassan Gilo (Latin roman script version)': 'mkd-sheikhhassangil-la',
        '(Macedonian) Sheikh Hassan Gilo (Latin roman script version with diacritical marks)': 'mkd-sheikhhassangil-lad',
        '(Macedonian) Sheikh Hassan Gilo': 'mkd-sheikhhassangil',
        '(Maltese) Martin R. Zammit, Muhammad El Sadi (Latin roman script version)': 'mlt-martinrzammitmu-la',
        '(Maltese) Martin R. Zammit, Muhammad El Sadi': 'mlt-martinrzammitmu',
        '(Maranao) Guro Alim Saromantang': 'mrw-guroalimsaroman',
        '(Malay) Abdullah Muhammad Basmeih': 'msa-abdullahmuhamma',
        '(Burmese) Alin U Yin': 'mya-alinuyin',
        '(Burmese) Ba Sein': 'mya-basein',
        '(Burmese) Ghazi Mohammad Hashim': 'mya-ghazimohammadha',
        '(Burmese) Hashim Tin Myint': 'mya-hashimtinmyint',
        '(Nepali) Ahl Al Hadith Central Society Of Nepal (Latin roman script version)': 'nep-ahlalhadithcent-la',
        '(Nepali) Ahl Al Hadith Central Society Of Nepal (Latin roman script version with diacritical marks)': 'nep-ahlalhadithcent-lad',
        '(Nepali) Ahl Al Hadith Central Society Of Nepal': 'nep-ahlalhadithcent',
        '(Dutch) Fred Leemhuis': 'nld-fredleemhuis',
        '(Dutch) Salomo Keyzer': 'nld-salomokeyzer',
        '(Dutch) Sofian S. Siregar': 'nld-sofianssiregar',
        '(Dutch) Van De Taal': 'nld-unknown',
        '(Norwegian) Einar Berg (Latin roman script version)': 'nor-einarberg-la',
        '(Norwegian) Einar Berg': 'nor-einarberg',
        '(Chichewa) Al Haji Yusuf Muhammad Kanyamula': 'nya-alhajiyusufmuha',
        '(Chichewa) Khaled Ibrahim Betala': 'nya-khaledibrahimbe',
        '(Oromo) Ghali Apapur Apaghuna': 'orm-ghaliapapurapag',
        '(Panjabi) Dr. Muhamad Habib, Bhai Harpreet Singh, Maulana Wahiduddin Khan (Latin roman script version)': 'pan-drmuhamadhabibb-la',
        '(Panjabi) Dr. Muhamad Habib, Bhai Harpreet Singh, Maulana Wahiduddin Khan (Latin roman script version with diacritical marks)': 'pan-drmuhamadhabibb-lad',
        '(Panjabi) Dr. Muhamad Habib, Bhai Harpreet Singh, Maulana Wahiduddin Khan': 'pan-drmuhamadhabibb',
        '(Polish) Jozefa Bielawskiego (Latin roman script version)': 'pol-jozefabielawski-la',
        '(Polish) Jozefa Bielawskiego': 'pol-jozefabielawski',
        '(Portuguese) Helmi Nasr (Latin roman script version)': 'por-helminasr-la',
        '(Portuguese) Helmi Nasr': 'por-helminasr',
        '(Portuguese) Samir El Hayek (Latin roman script version)': 'por-samirelhayek-la',
        '(Portuguese) Samir El Hayek': 'por-samirelhayek',
        '(Dari) Mawlawi Muhammad Anwar Badkhashani': 'prs-mawlawimuhammad',
        '(Pushto) Abdulwali Khan': 'pus-abdulwalikhan',
        '(Pushto) Zakaria Abulsalam': 'pus-zakariaabulsala',
        '(Romanian) George Grigore (Latin roman script version)': 'ron-georgegrigore-la',
        '(Romanian) George Grigore': 'ron-georgegrigore',
        '(Romanian) Hadi Abdollahian': 'ron-hadiabdollahian',
        '(Romanian) Unknown (Latin roman script version)': 'ron-unknown-la',
        '(Romanian) Unknown': 'ron-unknown',
        '(Rundi) Sheikh Amissi Radjabu Ntamba': 'run-sheikhamissirad',
        '(Russian) Abu Adel (Latin roman script version)': 'rus-abuadel-la',
        '(Russian) Abu Adel': 'rus-abuadel',
        '(Russian) Elmir Kuliev (Latin roman script version)': 'rus-elmirkuliev-la',
        '(Russian) Elmir Kuliev': 'rus-elmirkuliev',
        '(Russian) Gordy Semyonovich Sablukov (Latin roman script version)': 'rus-gordysemyonovic-la',
        '(Russian) Gordy Semyonovich Sablukov': 'rus-gordysemyonovic',
        '(Russian) Ignaty Yulianovich Krachkovsky (Latin roman script version)': 'rus-ignatyyulianovi-la',
        '(Russian) Ignaty Yulianovich Krachkovsky': 'rus-ignatyyulianovi',
        '(Russian) Magomed Nuri Osmanovich Osmanov (Latin roman script version)': 'rus-magomednuriosma-la',
        '(Russian) Magomed Nuri Osmanovich Osmanov': 'rus-magomednuriosma',
        '(Russian) Ministry Of Awqaf, Egypt (Latin roman script version)': 'rus-ministryofawqaf-la',
        '(Russian) Ministry Of Awqaf, Egypt': 'rus-ministryofawqaf',
        '(Russian) V. Porokhova (Latin roman script version)': 'rus-vporokhova-la',
        '(Russian) V. Porokhova': 'rus-vporokhova',
        '(Sinhala) Naseem Ismail And Masoor Maulana, Kaleel (Latin roman script version)': 'sin-naseemismailand-la',
        '(Sinhala) Naseem Ismail And Masoor Maulana, Kaleel (Latin roman script version with diacritical marks)': 'sin-naseemismailand-lad',
        '(Sinhala) Naseem Ismail And Masoor Maulana, Kaleel': 'sin-naseemismailand',
        '(Sinhala) Www.islamhouse.com (Latin roman script version)': 'sin-wwwislamhouseco-la',
        '(Sinhala) Www.islamhouse.com (Latin roman script version with diacritical marks)': 'sin-wwwislamhouseco-lad',
        '(Sinhala) Www.islamhouse.com': 'sin-wwwislamhouseco',
        '(Slovak) Hadi Abdollahian': 'slk-hadiabdollahian',
        '(Shona) Abdullah J. M. Adini And Students': 'sna-abdullahjmadini',
        '(Sindhi) Taj Mehmood Amroti': 'snd-tajmehmoodamrot',
        '(Somali) Abdullah Hasan Jacob': 'som-abdullahhasanja',
        '(Somali) Mahmud Muhammad Abduh': 'som-mahmudmuhammada',
        '(Somali) Shaykh Mahmood Muhammad Abdu': 'som-shaykhmahmoodmu',
        '(Sotho) Sheikh Elias Keketso Lelia': 'sot-sheikheliaskeke',
        '(Spanish) Abdul Qader Mouheddine, Sirhan Ali Sanchez. (Latin roman script version)': 'spa-abdulqadermouhe-la',
        '(Spanish) Abdul Qader Mouheddine, Sirhan Ali Sanchez.': 'spa-abdulqadermouhe',
        '(Spanish) Islamic Foundation (Latin roman script version)': 'spa-islamicfoundati-la',
        '(Spanish) Islamic Foundation': 'spa-islamicfoundati',
        '(Spanish) Islamic Foundation (Latin roman script version) 2': 'spa-islamicfoundati1-la',
        '(Spanish) Islamic Foundation 2': 'spa-islamicfoundati1',
        '(Spanish) Julio Cortes (Latin roman script version)': 'spa-juliocortes-la',
        '(Spanish) Julio Cortes': 'spa-juliocortes',
        '(Spanish) Muhammad Asad Abdurrasak Perez (Latin roman script version)': 'spa-muhammadasadabd-la',
        '(Spanish) Muhammad Asad Abdurrasak Perez': 'spa-muhammadasadabd',
        '(Spanish) Muhammad Isa Garcia (Latin roman script version)': 'spa-muhammadisagarc-la',
        '(Spanish) Muhammad Isa Garcia': 'spa-muhammadisagarc',
        '(Spanish) Raul Gonzalez Bornez (Latin roman script version)': 'spa-raulgonzalezbor-la',
        '(Spanish) Raul Gonzalez Bornez': 'spa-raulgonzalezbor',
        '(Albanian) Feti Mehdiu (Latin roman script version)': 'sqi-fetimehdiu-la',
        '(Albanian) Feti Mehdiu': 'sqi-fetimehdiu',
        '(Albanian) Hasan Efendi Nahi (Latin roman script version)': 'sqi-hasanefendinahi-la',
        '(Albanian) Hasan Efendi Nahi': 'sqi-hasanefendinahi',
        '(Albanian) Hassan Nahi (Latin roman script version)': 'sqi-hassannahi-la',
        '(Albanian) Hassan Nahi': 'sqi-hassannahi',
        '(Albanian) Sherif Ahmeti (Latin roman script version)': 'sqi-sherifahmeti-la',
        '(Albanian) Sherif Ahmeti': 'sqi-sherifahmeti',
        '(Albanian) Unknown (Latin roman script version)': 'sqi-unknown-la',
        '(Albanian) Unknown': 'sqi-unknown',
        '(Serbian) Rowwad Translation Center Islamhouse': 'srp-rowwadtranslati',
        '(Swahili) Abdullah Muhammad Abu Bakr': 'swa-abdullahmuhamma',
        '(Swahili) Ali Muhsin Al Barwani': 'swa-alimuhsinalbarw',
        '(Swedish) Knut Bernstrom (Latin roman script version)': 'swe-knutbernstrom-la',
        '(Swedish) Knut Bernstrom': 'swe-knutbernstrom',
        '(Tamil) Abdulhameed Baqavi (Latin roman script version)': 'tam-abdulhameedbaqa-la',
        '(Tamil) Abdulhameed Baqavi (Latin roman script version with diacritical marks)': 'tam-abdulhameedbaqa-lad',
        '(Tamil) Abdulhameed Baqavi': 'tam-abdulhameedbaqa',
        '(Tamil) Jan Turst Foundation (Latin roman script version)': 'tam-janturstfoundat-la',
        '(Tamil) Jan Turst Foundation (Latin roman script version with diacritical marks)': 'tam-janturstfoundat-lad',
        '(Tamil) Jan Turst Foundation': 'tam-janturstfoundat',
        '(Tatar) Yakub Ibn Nugman': 'tat-yakubibnnugman',
        '(Telugu) Abdul Raheem Mohammad Moulana (Latin roman script version)': 'tel-abdulraheemmoha-la',
        '(Telugu) Abdul Raheem Mohammad Moulana (Latin roman script version with diacritical marks)': 'tel-abdulraheemmoha-lad',
        '(Telugu) Abdul Raheem Mohammad Moulana': 'tel-abdulraheemmoha',
        '(Telugu) Muhammad Aziz Ur Rehman': 'tel-muhammadazizurr',
        '(Tajik) Abdolmohammad Ayati (Latin roman script version)': 'tgk-abdolmohammaday-la',
        '(Tajik) Abdolmohammad Ayati (Latin roman script version with diacritical marks)': 'tgk-abdolmohammaday-lad',
        '(Tajik) Abdolmohammad Ayati': 'tgk-abdolmohammaday',
        '(Tajik) Khoja Mirov (Latin roman script version)': 'tgk-khojamirov-la',
        '(Tajik) Khoja Mirov (Latin roman script version with diacritical marks)': 'tgk-khojamirov-lad',
        '(Tajik) Khoja Mirov': 'tgk-khojamirov',
        '(Tajik) Www.islamhouse.com (Latin roman script version)': 'tgk-wwwislamhouseco-la',
        '(Tajik) Www.islamhouse.com (Latin roman script version with diacritical marks)': 'tgk-wwwislamhouseco-lad',
        '(Tajik) Www.islamhouse.com': 'tgk-wwwislamhouseco',
        '(Thai) Group From The Society Of Graduates Of Thai Universities And Institutes (Latin roman script version)': 'tha-groupfromthesoc-la',
        '(Thai) Group From The Society Of Graduates Of Thai Universities And Institutes (Latin roman script version with diacritical marks)': 'tha-groupfromthesoc-lad',
        '(Thai) Group From The Society Of Graduates Of Thai Universities And Institutes': 'tha-groupfromthesoc',
        '(Thai) King Fahad Quran Complex (Latin roman script version)': 'tha-kingfahadquranc-la',
        '(Thai) King Fahad Quran Complex (Latin roman script version with diacritical marks)': 'tha-kingfahadquranc-lad',
        '(Thai) King Fahad Quran Complex': 'tha-kingfahadquranc',
        '(Turkish) Abdulbaki Golpinarli (Latin roman script version)': 'tur-abdulbakigolpin-la',
        '(Turkish) Abdulbaki Golpinarli': 'tur-abdulbakigolpin',
        '(Turkish) Adem Ugur (Latin roman script version)': 'tur-ademugur-la',
        '(Turkish) Adem Ugur': 'tur-ademugur',
        '(Turkish) Ali Bulac (Latin roman script version)': 'tur-alibulac-la',
        '(Turkish) Ali Bulac': 'tur-alibulac',
        '(Turkish) Ali Fikri Yavuz (Latin roman script version)': 'tur-alifikriyavuz-la',
        '(Turkish) Ali Fikri Yavuz': 'tur-alifikriyavuz',
        '(Turkish) Celal Y Ld R M (Latin roman script version)': 'tur-celalyldrm-la',
        '(Turkish) Celal Y Ld R M': 'tur-celalyldrm',
        '(Turkish) Diyanet Isleri (Latin roman script version)': 'tur-diyanetisleri-la',
        '(Turkish) Diyanet Isleri': 'tur-diyanetisleri',
        '(Turkish) Diyanet Isleri (Latin roman script version) 2': 'tur-diyanetisleri1-la',
        '(Turkish) Diyanet Isleri 2': 'tur-diyanetisleri1',
        '(Turkish) Diyanet Vakfi (Latin roman script version)': 'tur-diyanetvakfi-la',
        '(Turkish) Diyanet Vakfi': 'tur-diyanetvakfi',
        '(Turkish) Edip Yuksel (Latin roman script version)': 'tur-edipyuksel-la',
        '(Turkish) Edip Yuksel': 'tur-edipyuksel',
        '(Turkish) Elmalili Hamdi Yazir (Latin roman script version)': 'tur-elmalilihamdiya-la',
        '(Turkish) Elmalili Hamdi Yazir': 'tur-elmalilihamdiya',
        '(Turkish) Elmal L Sadelestirilmis (Latin roman script version)': 'tur-elmallsadelesti-la',
        '(Turkish) Elmal L Sadelestirilmis': 'tur-elmallsadelesti',
        '(Turkish) Elmal L Sadelestirilmis (Latin roman script version) 2': 'tur-elmallsadelesti1-la',
        '(Turkish) Elmal L Sadelestirilmis 2': 'tur-elmallsadelesti1',
        '(Turkish) Fizilal Il Kuran (Latin roman script version)': 'tur-fizilalilkuran-la',
        '(Turkish) Fizilal Il Kuran': 'tur-fizilalilkuran',
        '(Turkish) Gultekin Onan (Latin roman script version)': 'tur-gultekinonan-la',
        '(Turkish) Gultekin Onan': 'tur-gultekinonan',
        '(Turkish) Hasan Basri Cantay (Latin roman script version)': 'tur-hasanbasricanta-la',
        '(Turkish) Hasan Basri Cantay': 'tur-hasanbasricanta',
        '(Turkish) Ibni Kesir (Latin roman script version)': 'tur-ibnikesir-la',
        '(Turkish) Ibni Kesir': 'tur-ibnikesir',
        '(Turkish) Iskender Ali Mihr (Latin roman script version)': 'tur-iskenderalimihr-la',
        '(Turkish) Iskender Ali Mihr': 'tur-iskenderalimihr',
        '(Turkish) Latin Alphabet (Latin roman script version)': 'tur-latinalphabet-la',
        '(Turkish) Latin Alphabet': 'tur-latinalphabet',
        '(Turkish) Latin Alphabet (Latin roman script version) 2': 'tur-latinalphabet1-la',
        '(Turkish) Latin Alphabet 2': 'tur-latinalphabet1',
        '(Turkish) Muhammed Esed (Latin roman script version)': 'tur-muhammedesed-la',
        '(Turkish) Muhammed Esed': 'tur-muhammedesed',
        '(Turkish) Muhammet Abay (Latin roman script version)': 'tur-muhammetabay-la',
        '(Turkish) Muhammet Abay': 'tur-muhammetabay',
        '(Turkish) Muslim Shahin (Latin roman script version)': 'tur-muslimshahin-la',
        '(Turkish) Muslim Shahin': 'tur-muslimshahin',
        '(Turkish) Saban Piris (Latin roman script version)': 'tur-sabanpiris-la',
        '(Turkish) Saban Piris': 'tur-sabanpiris',
        '(Turkish) Shaban Britch (Latin roman script version)': 'tur-shabanbritch-la',
        '(Turkish) Shaban Britch': 'tur-shabanbritch',
        '(Turkish) Suat Yildirim (Latin roman script version)': 'tur-suatyildirim-la',
        '(Turkish) Suat Yildirim': 'tur-suatyildirim',
        '(Turkish) Suleyman Ates (Latin roman script version)': 'tur-suleymanates-la',
        '(Turkish) Suleyman Ates': 'tur-suleymanates',
        '(Turkish) Tefhim Ul Kuran (Latin roman script version)': 'tur-tefhimulkuran-la',
        '(Turkish) Tefhim Ul Kuran': 'tur-tefhimulkuran',
        '(Turkish) Www.islamhouse.com (Latin roman script version)': 'tur-wwwislamhouseco-la',
        '(Turkish) Www.islamhouse.com': 'tur-wwwislamhouseco',
        '(Turkish) Yasar Nuri Ozturk (Latin roman script version)': 'tur-yasarnuriozturk-la',
        '(Turkish) Yasar Nuri Ozturk': 'tur-yasarnuriozturk',
        '(Turkish) Yasar Nuri Ozturk (Latin roman script version) 2': 'tur-yasarnuriozturk1-la',
        '(Turkish) Yasar Nuri Ozturk 2': 'tur-yasarnuriozturk1',
        '(Turkish) Y. N. Ozturk (Latin roman script version)': 'tur-ynozturk-la',
        '(Turkish) Y. N. Ozturk': 'tur-ynozturk',
        '(Twi) Sheikh Haroun Ismaeel': 'twi-sheikhharounism',
        '(Uighur) Muhammad Saleh': 'uig-muhammadsaleh',
        '(Uighur) Shaykh Muhammad Saleh': 'uig-shaykhmuhammads',
        '(Ukrainian) Dr. Mikhailo Yaqubovic': 'ukr-drmikhailoyaqub',
        '(Ukrainian) Hadi Abdollahian (Latin roman script version)': 'ukr-hadiabdollahian-la',
        '(Ukrainian) Hadi Abdollahian': 'ukr-hadiabdollahian',
        '(Ukrainian) Mykhaylo Yakubovych (Latin roman script version)': 'ukr-mykhayloyakubov-la',
        '(Ukrainian) Mykhaylo Yakubovych': 'ukr-mykhayloyakubov',
        '(Ukrainian) Yakubovych (Latin roman script version)': 'ukr-yakubovych-la',
        '(Ukrainian) Yakubovych': 'ukr-yakubovych',
        '(Urdu) Abul Ala Maududi (Latin roman script version)': 'urd-abulaalamaududi-la',
        '(Urdu) Abul A Ala Maududi': 'urd-abulaalamaududi',
        '(Urdu) Ahmed Ali': 'urd-ahmedali',
        '(Urdu) Fateh Muhammad Jalandhry': 'urd-fatehmuhammadja',
        '(Urdu) Mahmood Ul Hassan': 'urd-mahmoodulhassan',
        '(Urdu) Muhammad Hussain Najafi': 'urd-muhammadhussain',
        '(Urdu) Muhammad Junagarhi (Latin roman script version)': 'urd-muhammadjunagar-la',
        '(Urdu) Muhammad Junagarhi': 'urd-muhammadjunagar',
        '(Urdu) Muhammad Junagarhi, Muhammad Kazim': 'urd-muhammadjunagar1',
        '(Urdu) Muhammad Karam Shah Al Azhari': 'urd-muhammadkaramsh',
        '(Urdu) Muhammad Tahir Ul Qadri': 'urd-muhammadtahirul',
        '(Urdu) Muhammad Taqi Usmani': 'urd-muhammadtaqiusm',
        '(Urdu) Syed Zeeshan Haider Jawadi': 'urd-syedzeeshanhaid',
        '(Uzbek) Alaaudeen Mansour': 'uzb-alaaudeenmansou',
        '(Uzbek) Alauddin Mansour': 'uzb-alauddinmansour',
        '(Uzbek) Muhammad Sodik Muhammad Yusuf': 'uzb-muhammadsodikmu',
        '(Vietnamese) Hassan Abdulkarim (Latin roman script version)': 'vie-hassanabdulkari-la',
        '(Vietnamese) Hassan Abdulkarim': 'vie-hassanabdulkari',
        '(Vietnamese) Rowwad Translation Center (Latin roman script version)': 'vie-rowwadtranslati-la',
        '(Vietnamese) Rowwad Translation Center': 'vie-rowwadtranslati',
        '(Xhosa) Imaam Ismaaeel Ngqoyiyana': 'xho-imaamismaaeelng',
        '(Yoruba) Shaykh Abu Rahimah Mikael Aykyuni (Latin roman script version)': 'yor-shaykhaburahima-la',
        '(Yoruba) Shaykh Abu Rahimah Mikael Aykyuni': 'yor-shaykhaburahima',
        '(Yau) Muhammad Bin Abdul Hamid Silika (Latin roman script version)': 'yuw-muhammadbinabdu-la',
        '(Yau) Muhammad Bin Abdul Hamid Silika': 'yuw-muhammadbinabdu',
        '(Chinese-traditional) Anonymous Group Of Translators (Latin roman script version)': 'zho-anonymousgroupo-la',
        '(Chinese-traditional) Anonymous Group Of Translators (Latin roman script version with diacritical marks)': 'zho-anonymousgroupo-lad',
        '(Chinese-traditional) Anonymous Group Of Translators': 'zho-anonymousgroupo',
        '(Chinese-simplified) Ma Jian (Latin roman script version)': 'zho-majian-la',
        '(Chinese-simplified) Ma Jian (Latin roman script version with diacritical marks)': 'zho-majian-lad',
        '(Chinese-simplified) Ma Jian': 'zho-majian',
        '(Chinese-traditional) Ma Jian (Latin roman script version)': 'zho-majian1-la',
        '(Chinese-traditional) Ma Jian (Latin roman script version with diacritical marks)': 'zho-majian1-lad',
        '(Chinese-traditional) Ma Jian': 'zho-majian1',
        '(Chinese-simplified) Ma Zhong Gang (Latin roman script version)': 'zho-mazhonggang-la',
        '(Chinese-simplified) Ma Zhong Gang (Latin roman script version with diacritical marks)': 'zho-mazhonggang-lad',
        '(Chinese-simplified) Ma Zhong Gang': 'zho-mazhonggang',
        '(Chinese-simplified) Muhammad Makin (Latin roman script version)': 'zho-muhammadmakin-la',
        '(Chinese-simplified) Muhammad Makin (Latin roman script version with diacritical marks)': 'zho-muhammadmakin-lad',
        '(Chinese-simplified) Muhammad Makin': 'zho-muhammadmakin',
        '(Zulu) Iqembu Lezifundiswa, Mussa Muhammad Telela , Uthman Mfanafuthi Msomi, Moulana Abdur Rahman Chilipa, Haji Ibrahim Mondli Japhet Mthembu, Moulana Imran Ngcobo, Moulana Eshaaq Osman': 'zul-iqembulezifundi'
    }

    HADITH = {
        '[Sunni] [Salafi] (Arabic) Sahih al Bukhari': 'ara-bukhari',
        '[Sunni] [Salafi] (Arabic) Sahih al Bukhari (2)': 'ara-bukhari1',
        '[Sunni] [Salafi] (Bengali) Sahih al Bukhari': 'ben-bukhari',
        '[Sunni] [Salafi] (English) Sahih al Bukhari': 'eng-bukhari',
        '[Sunni] [Salafi] (Indonesian) Sahih al Bukhari': 'ind-bukhari',
        '[Sunni] [Salafi] (Russian) Sahih al Bukhari': 'rus-bukhari',
        '[Sunni] [Salafi] (Tamil) Sahih al Bukhari': 'tam-bukhari',
        '[Sunni] [Salafi] (Turkish) Sahih al Bukhari': 'tur-bukhari',
        '[Sunni] [Salafi] (Urdu) Sahih al Bukhari': 'urd-bukhari',
        '[Sunni] [Salafi] (Arabic) Sahih Muslim': 'ara-muslim',
        '[Sunni] [Salafi] (Arabic) Sahih Muslim (2)': 'ara-muslim1',
        '[Sunni] [Salafi] (Bengali) Sahih Muslim': 'ben-muslim',
        '[Sunni] [Salafi] (English) Sahih Muslim': 'eng-muslim',
        '[Sunni] [Salafi] (French) Sahih Muslim': 'fra-muslim',
        '[Sunni] [Salafi] (Indonesian) Sahih Muslim': 'ind-muslim',
        '[Sunni] [Salafi] (Russian) Sahih Muslim': 'rus-muslim',
        '[Sunni] [Salafi] (Tamil) Sahih Muslim': 'tam-muslim',
        '[Sunni] [Salafi] (Turkish) Sahih Muslim': 'tur-muslim',
        '[Sunni] [Salafi] (Urdu) Sahih Muslim': 'urd-muslim',
        '[Sunni] [Salafi] (Arabic) Sunan an Nasai': 'ara-nasai',
        '[Sunni] [Salafi] (Arabic) Sunan an Nasai (2)': 'ara-nasai1',
        '[Sunni] [Salafi] (Bengali) Sunan an Nasai': 'ben-nasai',
        '[Sunni] [Salafi] (English) Sunan an Nasai': 'eng-nasai',
        '[Sunni] [Salafi] (Indonesian) Sunan an Nasai': 'ind-nasai',
        '[Sunni] [Salafi] (Turkish) Sunan an Nasai': 'tur-nasai',
        '[Sunni] [Salafi] (Urdu) Sunan an Nasai': 'urd-nasai',
        '[Sunni] [Salafi] (Arabic) Sunan Abu Dawud': 'ara-abudawud',
        '[Sunni] [Salafi] (Arabic) Sunan Abu Dawud (2)': 'ara-abudawud1',
        '[Sunni] [Salafi] (Bengali) Sunan Abu Dawud': 'ben-abudawud',
        '[Sunni] [Salafi] (English) Sunan Abu Dawud': 'eng-abudawud',
        '[Sunni] [Salafi] (Indonesian) Sunan Abu Dawud': 'ind-abudawud',
        '[Sunni] [Salafi] (Russian) Sunan Abu Dawud': 'rus-abudawud',
        '[Sunni] [Salafi] (Turkish) Sunan Abu Dawud': 'tur-abudawud',
        '[Sunni] [Salafi] (Urdu) Sunan Abu Dawud': 'urd-abudawud',
        '[Sunni] [Salafi] (Arabic) Jami At Tirmidhi': 'ara-tirmidhi',
        '[Sunni] [Salafi] (Arabic) Jami At Tirmidhi (2)': 'ara-tirmidhi1',
        '[Sunni] [Salafi] (Bengali) Jami At Tirmidhi': 'ben-tirmidhi',
        '[Sunni] [Salafi] (English) Jami At Tirmidhi': 'eng-tirmidhi',
        '[Sunni] [Salafi] (Indonesian) Jami At Tirmidhi': 'ind-tirmidhi',
        '[Sunni] [Salafi] (Turkish) Jami At Tirmidhi': 'tur-tirmidhi',
        '[Sunni] [Salafi] (Urdu) Jami At Tirmidhi': 'urd-tirmidhi',
        '[Sunni] [Salafi] (Arabic) Sunan Ibn Majah': 'ara-ibnmajah1',
        '[Sunni] [Salafi] (Bengali) Sunan Ibn Majah': 'ben-ibnmajah',
        '[Sunni] [Salafi] (English) Sunan Ibn Majah': 'eng-ibnmajah',
        '[Sunni] [Salafi] (Indonesian) Sunan Ibn Majah': 'ind-ibnmajah',
        '[Sunni] [Salafi] (Turkish) Sunan Ibn Majah': 'tur-ibnmajah',
        '[Sunni] [Salafi] (Urdu) Sunan Ibn Majah': 'urd-ibnmajah',
        '[Sunni] [Salafi] (Arabic) Forty Hadith of Shah Waliullah Dehlawi': 'ara-dehlawi',
        '[Sunni] [Salafi] (English) Forty Hadith of Shah Waliullah Dehlawi': 'eng-dehlawi',
        '[Sunni] [Salafi] (Arabic) Forty Hadith of an-Nawawi': 'ara-nawawi',
        '[Sunni] [Salafi] (Bengali) Forty Hadith of an-Nawawi': 'ben-nawawi',
        '[Sunni] [Salafi] (English) Forty Hadith of an-Nawawi': 'eng-nawawi',
        '[Sunni] [Salafi] (Arabic) Forty Hadith Qudsi': 'ara-qudsi',
        '[Sunni] [Salafi] (English) Forty Hadith Qudsi': 'eng-qudsi',

        # Malikis

        '[Sunni] [Salafi] (Arabic) Muwatta Malik': 'ara-malik',
        '[Sunni] [Salafi] (Arabic) Muwatta Malik (2)': 'ara-malik1',
        '[Sunni] [Salafi] (Bengali) Muwatta Malik': 'ben-malik',
        '[Sunni] [Salafi] (English) Muwatta Malik': 'eng-malik',
        '[Sunni] [Salafi] (French) Muwatta Malik': 'fra-malik',
        '[Sunni] [Salafi] (Indonesian) Muwatta Malik': 'ind-malik',
        '[Sunni] [Salafi] (Turkish) Muwatta Malik': 'tur-malik',
        '[Sunni] [Salafi] (Urdu) Muwatta Malik': 'urd-malik',

        # Shia

        '[Shia] (English) Al-Amālī (Muḥammad al-Mufīd)': 'en-Al-Amali-Mufid',
        '[Shia] (English) Al-Amālī (ʿAlī al-Ṣaduq)': 'en-Al-Amali-Saduq',
        '[Shia] (English) Al-Kāfi - Volume 1': 'en-Al-Kafi-Volume-1-Kulayni',
        '[Shia] (English) Al-Kāfi - Volume 2': 'en-Al-Kafi-Volume-2-Kulayni',
        '[Shia] (English) Al-Kāfi - Volume 3': 'en-Al-Kafi-Volume-3-Kulayni',
        '[Shia] (English) Al-Kāfi - Volume 4': 'en-Al-Kafi-Volume-4-Kulayni',
        '[Shia] (English) Al-Kāfi - Volume 5': 'en-Al-Kafi-Volume-5-Kulayni',
        '[Shia] (English) Al-Kāfi - Volume 6': 'en-Al-Kafi-Volume-6-Kulayni',
        '[Shia] (English) Al-Kāfi - Volume 7': 'en-Al-Kafi-Volume-7-Kulayni',
        '[Shia] (English) Al-Kāfi - Volume 8': 'en-Al-Kafi-Volume-8-Kulayni',
        '[Shia] (English) Al-Khiṣāl': 'en-Al-Khisal-Saduq',
        '[Shia] (English) Al-Tawḥīd': 'en-Al-Tawhid-Saduq',
        '[Shia] (English) Faḍaʾil al-Shīʿa': 'en-Fadail-al-Shia-Saduq',
        '[Shia] (English) Kāmil al-Ziyārāt': 'en-Kamil-al-Ziyarat-Qummi',
        '[Shia] (English) Kitāb al-Ḍuʿafāʾ': 'en-Kitab-al-Duafa-Ghadairi',
        '[Shia] (English) Kitāb al-Ghayba (Ibrāhīm al-Nuʿmānī)': 'en-Kitab-al-Ghayba-Numani',
        '[Shia] (English) Kitāb al-Ghayba (al-Ḥasan al-Ṭūsī)': 'en-Kitab-al-Ghayba-Tusi',
        '[Shia] (English) Kitāb al-Muʾmin': 'en-Kitab-al-Mumin-Ahwazi',
        '[Shia] (English) Kitāb al-Zuhd': 'en-Kitab-al-Zuhd-Ahwazi',
        '[Shia] (English) Maʿānī al-ʾAkhbār': 'en-Maani-al-Akhbar-Saduq',
        '[Shia] (English) Muʿjam al-Aḥādīth al-Muʿtabara': 'en-Mujam-al-Ahadith-al-Mutabara-Muhsini',
        '[Shia] (English) Nahj al-Balāgha': 'en-Nahj-al-Balagha-Radi',
        '[Shia] (English) Risālat al-Ḥuqūq': 'en-Risalat-al-Huquq-Abidin',
        '[Shia] (English) Ṣifāt al-Shīʿa': 'en-Sifat-al-Shia-Saduq',
        '[Shia] (English) Thawāb al-Aʿmāl wa ʿiqāb al-Aʿmāl': 'en-Thawab-al-Amal-wa-iqab-al-Amal-Saduq',
        '[Shia] (English) ʿUyūn akhbār al-Riḍā - Volume 1': 'en-Uyun-akhbar-al-Rida-Volume-1-Saduq',
        '[Shia] (English) ʿUyūn akhbār al-Riḍā - Volume 2': 'en-Uyun-akhbar-al-Rida-Volume-2-Saduq',

        '[Shia] (Arabic) Al-Amālī (Muḥammad al-Mufīd)': 'ar-Al-Amali-Mufid',
        '[Shia] (Arabic) Al-Amālī (ʿAlī al-Ṣaduq)': 'ar-Al-Amali-Saduq',
        '[Shia] (Arabic) Al-Kāfi - Volume 1': 'ar-Al-Kafi-Volume-1-Kulayni',
        '[Shia] (Arabic) Al-Kāfi - Volume 2': 'ar-Al-Kafi-Volume-2-Kulayni',
        '[Shia] (Arabic) Al-Kāfi - Volume 3': 'ar-Al-Kafi-Volume-3-Kulayni',
        '[Shia] (Arabic) Al-Kāfi - Volume 4': 'ar-Al-Kafi-Volume-4-Kulayni',
        '[Shia] (Arabic) Al-Kāfi - Volume 5': 'ar-Al-Kafi-Volume-5-Kulayni',
        '[Shia] (Arabic) Al-Kāfi - Volume 6': 'ar-Al-Kafi-Volume-6-Kulayni',
        '[Shia] (Arabic) Al-Kāfi - Volume 7': 'ar-Al-Kafi-Volume-7-Kulayni',
        '[Shia] (Arabic) Al-Kāfi - Volume 8': 'ar-Al-Kafi-Volume-8-Kulayni',
        '[Shia] (Arabic) Al-Khiṣāl': 'ar-Al-Khisal-Saduq',
        '[Shia] (Arabic) Al-Tawḥīd': 'ar-Al-Tawhid-Saduq',
        '[Shia] (Arabic) Faḍaʾil al-Shīʿa': 'ar-Fadail-al-Shia-Saduq',
        '[Shia] (Arabic) Kāmil al-Ziyārāt': 'ar-Kamil-al-Ziyarat-Qummi',
        '[Shia] (Arabic) Kitāb al-Ḍuʿafāʾ': 'ar-Kitab-al-Duafa-Ghadairi',
        '[Shia] (Arabic) Kitāb al-Ghayba (Ibrāhīm al-Nuʿmānī)': 'ar-Kitab-al-Ghayba-Numani',
        '[Shia] (Arabic) Kitāb al-Ghayba (al-Ḥasan al-Ṭūsī)': 'ar-Kitab-al-Ghayba-Tusi',
        '[Shia] (Arabic) Kitāb al-Muʾmin': 'ar-Kitab-al-Mumin-Ahwazi',
        '[Shia] (Arabic) Kitāb al-Zuhd': 'ar-Kitab-al-Zuhd-Ahwazi',
        '[Shia] (Arabic) Maʿānī al-ʾAkhbār': 'ar-Maani-al-Akhbar-Saduq',
        '[Shia] (Arabic) Muʿjam al-Aḥādīth al-Muʿtabara': 'ar-Mujam-al-Ahadith-al-Mutabara-Muhsini',
        '[Shia] (Arabic) Nahj al-Balāgha': 'ar-Nahj-al-Balagha-Radi',
        '[Shia] (Arabic) Risālat al-Ḥuqūq': 'ar-Risalat-al-Huquq-Abidin',
        '[Shia] (Arabic) Ṣifāt al-Shīʿa': 'ar-Sifat-al-Shia-Saduq',
        '[Shia] (Arabic) Thawāb al-Aʿmāl wa ʿiqāb al-Aʿmāl': 'ar-Thawab-al-Amal-wa-iqab-al-Amal-Saduq',
        '[Shia] (Arabic) ʿUyūn akhbār al-Riḍā - Volume 1': 'ar-Uyun-akhbar-al-Rida-Volume-1-Saduq',
        '[Shia] (Arabic) ʿUyūn akhbār al-Riḍā - Volume 2': 'ar-Uyun-akhbar-al-Rida-Volume-2-Saduq',
    }

    TAFSIR = {
        '(English) Tafsir Ibn Kathir (abridged)': 'en-tafisr-ibn-kathir',
        '(English) Maarif-ul-Quran': 'en-tafsir-maarif-ul-quran',
        '(English) Tazkirul Quran(Maulana Wahiduddin Khan)': 'en-tazkirul-quran',
        '(English) Kashf Al-Asrar Tafsir': 'en-kashf-al-asrar-tafsir',
        '(English) Al Qushairi Tafsir': 'en-al-qushairi-tafsir',
        '(English) Kashani Tafsir': 'en-kashani-tafsir',
        '(English) Tafsir al-Tustari': 'en-tafsir-al-tustari',
        '(English) Asbab Al-Nuzul by Al-Wahidi': 'en-asbab-al-nuzul-by-al-wahidi',
        '(English) Tanwîr al-Miqbâs min Tafsîr Ibn ‘Abbâs': 'en-tafsir-ibn-abbas',
        '(English) Al-Jalalayn': 'en-al-jalalayn',
        '(Arabic) Tafsir Ibn Kathir': 'ar-tafsir-ibn-kathir',
        '(Arabic) Tafseer Al Saddi': 'ar-tafseer-al-saddi',
        '(Arabic) Tafseer Al-Baghawi': 'ar-tafsir-al-baghawi',
        '(Arabic) Tafseer Tanwir al-Miqbas': 'ar-tafseer-tanwir-al-miqbas',
        '(Arabic) Tafsir Al Wasit': 'ar-tafsir-al-wasit',
        '(Arabic) Tafsir al-Tabari': 'ar-tafsir-al-tabari',
        '(Arabic) Tafsir Muyassar': 'ar-tafsir-muyassar',
        '(Arabic) Tafseer Al Qurtubi': 'ar-tafseer-al-qurtubi',
        '(Urdu) Fi Zilal al-Quran': 'ur-tafsir-fe-zalul-quran-syed-qatab',
        '(Urdu) Tafsir Ibn Kathir': 'ur-tafseer-ibn-e-kaseer',
        '(Urdu) Tafsir Bayan ul Quran': 'ur-tafsir-bayan-ul-quran',
        '(Urdu) Tazkirul Quran(Maulana Wahiduddin Khan)': 'ur-tazkirul-quran',
        '(Bengali) Tafsir Fathul Majid': 'bn-tafisr-fathul-majid',
        '(Bengali) Tafseer ibn Kathir': 'bn-tafseer-ibn-e-kaseer',
        '(Bengali) Tafsir Ahsanul Bayaan': 'bn-tafsir-ahsanul-bayaan',
        '(Bengali) Tafsir Abu Bakr Zakaria': 'bn-tafsir-abu-bakr-zakaria',
        '(Russian) Tafseer Al Saddi': 'ru-tafseer-al-saddi',
        '(Kurdish) Rebar Kurdish Tafsir': 'kurd-tafsir-rebar',
    }


class Titles:
    BIBLE = [
        # OT

        'Genesis',
        'Exodus',
        'Leviticus',
        'Numbers',
        'Deuteronomy',
        'Joshua',
        'Judges',
        'Ruth',
        '1 Samuel',
        '2 Samuel',
        '1 Kings',
        '2 Kings',
        '1 Chronicles',
        '2 Chronicles',
        'Ezra',
        'Nehemiah',
        'Esther',
        'Job',
        'Psalm',
        'Proverbs',
        'Ecclesiastes',
        'Song of Songs',
        'Isaiah',
        'Jeremiah',
        'Lamentations',
        'Ezekiel',
        'Daniel',
        'Hosea',
        'Joel',
        'Amos',
        'Obadiah',
        'Jonah',
        'Micah',
        'Nahum',
        'Habakkuk',
        'Zephaniah',
        'Haggai',
        'Zechariah',
        'Malachi',

        # NT

        'Matthew',
        'Mark',
        'Luke',
        'John',
        'Acts',
        'Romans',
        '1 Corinthians',
        '2 Corinthians',
        'Galatians',
        'Ephesians',
        'Philippians',
        'Colossians',
        '1 Thessalonians',
        '2 Thessalonians',
        '1 Timothy',
        '2 Timothy',
        'Titus',
        'Philemon',
        'Hebrews',
        'James',
        '1 Peter',
        '2 Peter',
        '1 John',
        '2 John',
        '3 John',
        'Jude',
        'Revelation',

        # Deuterocanon

        'Tobit',
        'Judith',
        'Greek Esther',
        'Sirach',
        'Wisdom',
        'Wisdom of Ben Sira',
        'Ecclesiasticus',
        'Baruch',
        'Letter of Jeremiah',
        'Prayer of Azariah',
        'Susanna',
        'Bel and the Dragon',
        '1 Maccabees',
        '2 Maccabees',
        '3 Maccabees',
        '4 Maccabees',
        '1 Esdras',
        '2 Esdras',
        'Psalm 151',
        'Prayer of Manasseh',
    ]

    SURAH = {
        1: '1. Al-Fatiha (The Opening)',
        2: '2. Al-Baqarah (The Cow)',
        3: '3. Al-Imran (The Family Of Imran)',
        4: '4. An-Nisa (The Women)',
        5: '5. Al-Maidah (The Table Spread)',
        6: '6. Al-An\'am (The Cattle)',
        7: '7. Al-A\'raf (The Heights)',
        8: '8. Al-Anfal (The Spoils of War)',
        9: '9. At-Taubah (The Repentance)',
        10: '10. Yunus (Prophet Jonah)',
        11: '11. Hud (Prophet Hud)',
        12: '12. Yusuf (Prophet Joseph)',
        13: '13. Ar-Rad (The Thunder)',
        14: '14. Ibrahim (Prophet Abraham)',
        15: '15. Al-Hijr (The Rocky Tract)',
        16: '16. An-Nahl (The Bee)',
        17: '17. Al-Isra (The Night Journey)',
        18: '18. Al-Kahf (The Cave)',
        19: '19. Maryam (Mary)',
        20: '20. Ta-Ha (Ta-Ha)',
        21: '21. Al-Anbiya (The Prophets)',
        22: '22. Al-Hajj (The Pilgrimage)',
        23: '23. Al-Mu\'minun (The Believers)',
        24: '24. Al-Noor (The Light)',
        25: '25. Al-Furqan (The Criterion)',
        26: '26. Al-Shuara (The Poets)',
        27: '27. Al-Naml (The Ants)',
        28: '28. Al-Qasas (The Stories)',
        29: '29. Al-Ankaboot (The Spider)',
        30: '30. Al-Room (The Romans)',
        31: '31. Luqman (Luqman)',
        32: '32. As-Sajda (The Prostration)',
        33: '33. Al-Ahzab (The Coalition)',
        34: '34. Saba (Sheva)',
        35: '35. Fatir (Originator)',
        36: '36. Ya-Seen (Yaseen)',
        37: '37. As-Saaffat (Those Who Set The Ranks)',
        38: '38. Sad (The Arabic Letter Sad)',
        39: '39. Az-Zumar (The Companies)',
        40: '40. Gafir (The Forgiver)',
        41: '41. Fussilat (Explained in Detail)',
        42: '42. Ash-Shura (Council)',
        43: '43. Az-Zukhruf (The Ornaments of Gold)',
        44: '44. Ad-Dukhan (The Smoke)',
        45: '45. Al-Jasiyah (The Kneeling)',
        46: '46. Al-Ahqaf (The Sandhills)',
        47: '47. Muhammad (Muhammad)',
        48: '48. Al-Fath (The Victory)',
        49: '49. Al-Hujuraat (The Apartments)',
        50: '50. Qaf (The Letter Qaf)',
        51: '51. Adh-Dhariyat (The Scatterers)',
        52: '52. At-Tur (The Mountain)',
        53: '53. An-Najm (The Star)',
        54: '54. Al-Qamar (The Moon)',
        55: '55. Ar-Rahman (The Most Gracious)',
        56: '56. Al-Waqiah (The Event)',
        57: '57. Al-Hadid (The Iron)',
        58: '58. Al-Mujadilah (The Pleading Woman)',
        59: '59. Al-Hashr (The Banishment)',
        60: '60. Al-Mumtahanah (The Woman Who Is Examined)',
        61: '61. As-Saff (The Ranks)',
        62: '62. Al-Jumua (The Congregation',
        63: '63. Al-Munafiqoon (The Hypocrites)',
        64: '64. At-Taghabun (The Manifestation of Losses)',
        65: '65. At-Talaq (Divorce)',
        66: '66. At-Tahrim (The Prohibition)',
        67: '67. Al-Mulk (The Kingdom)',
        68: '68. Al-Qalam (The Pen)',
        69: '69. Al-Haqqah (The Sure Truth)',
        70: '70. Al-Ma\'arij (The Ways of Ascent)',
        71: '71. Nuh (Prophet Noah)',
        72: '72. Al-Jinn (The Jinn)',
        73: '73. Al-Muzzammil (The One Covering Himself)',
        74: '74. Al-Muddaththir (The One Wrapping Himself Up)',
        75: '75. Al-Qiyamah (The Resurrection)',
        76: '76. Al-Insan (The Man)',
        77: '77. Al-Mursalaat (Those sent forth)',
        78: '78. An-Naba (The News)',
        79: '79. An-Naziat (Those Who Pull Out)',
        80: '80. Abasa (He Frowned)',
        81: '81. At-Takwir (The Overthrowing)',
        82: '82. Al-Infitaar (The Splitting Asunder)',
        83: '83. Al-Mutaffifin (The Defrauding)',
        84: '84. Al-Inshiqaq (The Splitting Asunder)',
        85: '85. Al-Burooj (The Big Stars)',
        86: '86. At-Tariq (The Night Comer)',
        87: '87. Al-Ala (The Most High)',
        88: '88. Al-Ghaashiyah (The Overwhelming)',
        89: '89. Al-Fajr (The Dawn)',
        90: '90. Al-Balad (The City)',
        91: '91. Ash-Shams (The Sun)',
        92: '92. Al-Lail (The Night)',
        93: '93. Ad-Duha (The Early Hours)',
        94: '94. Al-Inshirah (The Opening Up)',
        95: '95. At-Tin (The Fig)',
        96: '96. Al-Alaq (The Clot)',
        97: '97. Al-Qadr (The Majesty)',
        98: '98. Al-Bayyinah (The Clear Evidence)',
        99: '99. Az-Zalzalah (The Shaking)',
        100: '100. Al-Adiyat (The Assaulters)',
        101: '101. Al-Qari\'ah (The Calamity)',
        102: '102. At-Takathur (The Rivalry in World Increase)',
        103: '103. Al-Asr (The Time)',
        104: '104. Al-Humazah (The Slanderer)',
        105: '105. Al-Fil (The Elephant)',
        106: '106. Quraish (Quraish)',
        107: '107. Al-Maun (Act of Kindness)',
        108: '108. Al-Kauthar (The Abundance)',
        109: '109. Al-Kafirun (The Disbelievers)',
        110: '110. An-Nasr (The Help)',
        111: '111. Al-Masad (The Palm Fiber)',
        112: '112. Al-Ikhlas (The Unity)',
        113: '113. Al-Falaq (The Dawn)',
        114: '114. An-Nas (Mankind)'
    }


class IslamBranch:
    SUNNI = 0
    SHIA = 1
